class Fight < ActiveRecord::Base
  belongs_to :user
  belongs_to :fighter

  def self.fight_set_up
    Fight.last.fighter_id
    Fight.last.user_id
    Fight.fight?
  end

  def self.imager_lost
    puts "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMNkl:::ldKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMW0c.      .lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWx.          ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMK,          .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNo           '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWKxoodd'          .dWMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMKl.                :KMMWOl;,,:o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMX:            ..  .dXWWKl.      .lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMx.            '::ck00x:.         '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMWo                ....       . ..;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMWx.                     .'cx0000KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMM0'                ..,cx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMX:                lXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWd.              .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMM
MMMMMMMMMMMMM0,              .kMMMMWWNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOdc;;cxXMMMMMMMMMMMM
MMMMMMMMMMMMMWk.              oXKko:,',:dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,.      ;0MMMMMMMMMMM
MMMMMMMMMMMMMMWo.             .'.        ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'         oWMMMMMMMMMM
MMMMMMMMMMMMMMMK,                        cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.        .xWMMMMMMMMMM
MMMMMMMMMMMMMMMN:                ;ll;',ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK0KKXo.        ;KMMMMMMMMMMM
MMMMMMMMMMMMMMMNl                .:kXNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l,......        .dWMMMMMMMMMMM
MMMMMMMMMMMMMMMWd.                 .cxO00NMMMMMMMMMMMMMMMMMMMMMMMMMXl.                .OMMMMMMMMMMMM
MMMMMMMMMMMMMMMWo                       .,cldOKWMMMMMMMMMMMMMMMMWKo'                  .OMMMMMMMMMMMM
MMMMMMMMMMMMMMMO'                             .,cxO0NMMMMMMMMMW0c.                     lNMMMMMMMMMMM
MMMMMMMMMMMMMMMK:                                  .,lONMMMMNk:.                       .oNMMMMMMMMMM
MMMMMMMMMMMMMMMMO.                                    .cXN0l'                           .oNMMMMMMMMM
MMMMMMMMMMMMMMMWo                                       ',.    .;;.                      .kMMMMMMMMM
MMMMMMMMMMMMMMMK;            ...;dxd:.                       .c0WNl                      .kMMMMMMMMM
MMMMMMMMMMMMMMMx.         ..'odk0Oo;.      ..,;cl'         .xXWMMO,                      cNMMMMMMMMM
MMMMMMMMMMMMMMX:        .o0o.....    .,codkKXWWMM0d:.  .. .dWMMWO,                      :KMMMMMMMMMM
MMMMMMMMMMMMMMO.       .dWX;      .:xKWMMMMMMMMMMMMNOdxKX0KWMMNx.              ..      ;KMMMMMMMMMMM
MMMMMMMMMMMMMWd       .dNNo    .;dKWMMMMMMMMMMMMMMMMMMMMMMMMMNd.                      .kMMMMMMMMMMMM
MMMMMMMMMMMMMNc      .xWMO.  .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMXo'.                      .xWMMMMMMMMMMMM
MMMMMMMMMMMMMX;      oNMNl  ;OWMMMMMMMMMMMMMMMMMMMMMMMMMMNk,                        ;OWMMMMMMMMMMMMM
MMMMMMMMMMMMWk.     ;KMMXc,xNMMMMMMMMMMMMMMMMMMMMMMMMMMNk:.                   ..  'dXMMMMMMMMMMMMMMM
MMMMMMMMMMMXl.     'OMMMWXXMMMMMMMMMMMMMMMMMMMMMMMMMMW0:.                    .xXOONMMMMMMMMMMMMMMMMM
MMMMMMMMMMXc      :0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.                      .OMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMK,    .lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.                       .xMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMX;    :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKx:                         .OMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMNc   .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;                           ,KMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWl   lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;           .:kOo::'         ;XMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWo  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;          .;kNMMMMMK;       .xWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMNc  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,         .l0WMMMMMMMWd.      'OMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMO.  .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc        .dXWMMMMMMMMMMO.      ,KMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMNl   ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:       ,0WMMMMMMMMMMMMK,      ,KMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMM0'   ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:      .xWMMMMMMMMMMMMMNc      ,0MMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMWd.   ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMM0'      '0MMMMMMMMMMMMMMMk.     .kMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMk.   .OMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.      ,KMMMMMMMMMMMMMMMNo.     oWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMWx'  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMNc      .oWMMMMMMMMMMMMMMMMXc     .dNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWXkodXMMMMMMMMMMMMMMMMMMMMMMMMMMMK,     .cXMMMMMMMMMMMMMMMMMMXl.    .oNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.    ;xKMMMMMMMMMMMMMMMMMMMMXc     .kMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.   .kWMMMMMMMMMMMMMMMMMMMMMMk.     cNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl    lNMMMMMMMMMMMMMMMMMMMMMMMNl     ,KMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,   ,KMMMMMMMMMMMMMMMMMMMMMMMMMK;    '0MMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl    oWMMMMMMMMMMMMMMMMMMMMMMMMMMk.   .kMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.    oWMMMMMMMMMMMMMMMMMMMMMMMMMMNo   .kMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.     ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMK;  .xMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.  .;lxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMWo   oWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx. 'xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo   'OMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:.'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,   .xWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,   .oXMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd:;;ckWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".colorize(:red)
  end

  def self.imager_won
    puts "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMNkl:::ldKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMW0c.      .lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWx.          ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMK,          .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNo           '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWKxoodd'          .dWMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMKl.                :KMMWOl;,,:o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMX:            ..  .dXWWKl.      .lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMx.            '::ck00x:.         '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMWo                ....       . ..;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMWx.                     .'cx0000KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMM0'                ..,cx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMX:                lXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWd.              .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMM
MMMMMMMMMMMMM0,              .kMMMMWWNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOdc;;cxXMMMMMMMMMMMM
MMMMMMMMMMMMMWk.              oXKko:,',:dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,.      ;0MMMMMMMMMMM
MMMMMMMMMMMMMMWo.             .'.        ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'         oWMMMMMMMMMM
MMMMMMMMMMMMMMMK,                        cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.        .xWMMMMMMMMMM
MMMMMMMMMMMMMMMN:                ;ll;',ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK0KKXo.        ;KMMMMMMMMMMM
MMMMMMMMMMMMMMMNl                .:kXNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l,......        .dWMMMMMMMMMMM
MMMMMMMMMMMMMMMWd.                 .cxO00NMMMMMMMMMMMMMMMMMMMMMMMMMXl.                .OMMMMMMMMMMMM
MMMMMMMMMMMMMMMWo                       .,cldOKWMMMMMMMMMMMMMMMMWKo'                  .OMMMMMMMMMMMM
MMMMMMMMMMMMMMMO'                             .,cxO0NMMMMMMMMMW0c.                     lNMMMMMMMMMMM
MMMMMMMMMMMMMMMK:                                  .,lONMMMMNk:.                       .oNMMMMMMMMMM
MMMMMMMMMMMMMMMMO.                                    .cXN0l'                           .oNMMMMMMMMM
MMMMMMMMMMMMMMMWo                                       ',.    .;;.                      .kMMMMMMMMM
MMMMMMMMMMMMMMMK;            ...;dxd:.                       .c0WNl                      .kMMMMMMMMM
MMMMMMMMMMMMMMMx.         ..'odk0Oo;.      ..,;cl'         .xXWMMO,                      cNMMMMMMMMM
MMMMMMMMMMMMMMX:        .o0o.....    .,codkKXWWMM0d:.  .. .dWMMWO,                      :KMMMMMMMMMM
MMMMMMMMMMMMMMO.       .dWX;      .:xKWMMMMMMMMMMMMNOdxKX0KWMMNx.              ..      ;KMMMMMMMMMMM
MMMMMMMMMMMMMWd       .dNNo    .;dKWMMMMMMMMMMMMMMMMMMMMMMMMMNd.                      .kMMMMMMMMMMMM
MMMMMMMMMMMMMNc      .xWMO.  .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMXo'.                      .xWMMMMMMMMMMMM
MMMMMMMMMMMMMX;      oNMNl  ;OWMMMMMMMMMMMMMMMMMMMMMMMMMMNk,                        ;OWMMMMMMMMMMMMM
MMMMMMMMMMMMWk.     ;KMMXc,xNMMMMMMMMMMMMMMMMMMMMMMMMMMNk:.                   ..  'dXMMMMMMMMMMMMMMM
MMMMMMMMMMMXl.     'OMMMWXXMMMMMMMMMMMMMMMMMMMMMMMMMMW0:.                    .xXOONMMMMMMMMMMMMMMMMM
MMMMMMMMMMXc      :0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.                      .OMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMK,    .lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.                       .xMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMX;    :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKx:                         .OMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMNc   .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;                           ,KMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWl   lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;           .:kOo::'         ;XMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWo  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;          .;kNMMMMMK;       .xWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMNc  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,         .l0WMMMMMMMWd.      'OMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMO.  .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc        .dXWMMMMMMMMMMO.      ,KMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMNl   ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:       ,0WMMMMMMMMMMMMK,      ,KMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMM0'   ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:      .xWMMMMMMMMMMMMMNc      ,0MMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMWd.   ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMM0'      '0MMMMMMMMMMMMMMMk.     .kMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMk.   .OMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.      ,KMMMMMMMMMMMMMMMNo.     oWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMWx'  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMNc      .oWMMMMMMMMMMMMMMMMXc     .dNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWXkodXMMMMMMMMMMMMMMMMMMMMMMMMMMMK,     .cXMMMMMMMMMMMMMMMMMMXl.    .oNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.    ;xKMMMMMMMMMMMMMMMMMMMMXc     .kMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.   .kWMMMMMMMMMMMMMMMMMMMMMMk.     cNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl    lNMMMMMMMMMMMMMMMMMMMMMMMNl     ,KMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,   ,KMMMMMMMMMMMMMMMMMMMMMMMMMK;    '0MMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl    oWMMMMMMMMMMMMMMMMMMMMMMMMMMk.   .kMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.    oWMMMMMMMMMMMMMMMMMMMMMMMMMMNo   .kMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.     ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMK;  .xMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.  .;lxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMWo   oWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx. 'xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo   'OMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:.'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,   .xWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,   .oXMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd:;;ckWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".colorize(:green)
  end


  def self.fight?
    puts "Do you want to fight? \n
    Type 'Y' for Yes, 'N' for No".colorize(:white)
    input = gets.chomp
    if input.downcase == "y"
      Fight.fight_night
    else
      puts "Okay, let's go back to the Main Menu".colorize(:white)
      main_menu
    end
  end

  def self.fight_night
    ufc_fighter = Fight.last.fighter_id
    user_fighter = Fight.last.user_id
    opponent = Fighter.find(ufc_fighter)
    user = User.find(user_fighter)
    sleep 1.0

    if opponent.rating > user.rating
      Fight.imager_lost
      sleep 0.5
      puts "You Lost. I suppose that isn't too surprising, considering these are professionals and you're here by accident.".colorize(:red)

      opponent.update(wins: opponent.wins += 1)
      user.update(losses: user.losses += 1)

      opponent.fighter_rating_update
      user.user_rating_update

      main_menu
    else
      Fight.imager_won
      puts "You won! Wow, that was unexpected.".colorize(:white)



      user.update(wins: user.wins += 1)
      opponent.update(losses: opponent.losses += 1)
      opponent.fighter_rating_update
      user.user_rating_update

      main_menu
    end
  end


end
